GET https://asia-southeast2-sejutacita-app.cloudfunctions.net/fee-assessment-categories

###

GET https://asia-southeast2-sejutacita-app.cloudfunctions.net/fee-assessment-books?categoryId=11&page=4&size=999